name: axon
description: A starter flutter project to help quickly initialize
             a new project with AKWAD common tools and Architecture.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^4.0.4
  shared_preferences: ^0.5.7+1
  package_info: 0.4.0+16
  flutter_localizations:
    sdk: flutter
  auto_route: 
    git:
      url: https://github.com/AKWAD-Dragons/auto_route_library.git
      ref: fix-null-root
      path: auto_route
  rxdart: ^0.24.1
  json_annotation: ^3.0.0
  flutter_svg: ^0.17.0
  flutter_image_compress: ^0.6.5
  flutter_keyboard_visibility: ^3.2.1
  path_provider: 1.6.5
  flutter_device_locale: 0.4.0
  percent_indicator: ^2.1.7+4
  searchable_dropdown: ^1.1.3
  persistent_bottom_nav_bar: ^2.1.0
  cached_network_image: ^2.3.3
  flare_flutter: ^2.0.6
  toast: 0.1.5
  carousel_slider: ^2.3.1
  dotted_line: ^2.0.2

  # In-house packages
  auth_provider: ^1.0.2
  fly_networking: ^2.0.2
  # custom_form_builder: ^1.0.0-dev.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.4
  flutter_launcher_icons: ^0.7.3
  auto_route_generator: 
    git:
      url: https://github.com/AKWAD-Dragons/auto_route_library.git
      ref: fix-null-root
      path: auto_route_generator
  build_runner: ^1.7.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Black.ttf
          weight: 900
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 500

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 500


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/ic_launcher.png"
  adaptive_icon_foreground: "assets/launcher/ic_launcher.png"
  adaptive_icon_background: "#00ffffff"
